### ISSUE TITLE
Weird route(s)

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#23]
1.
~~https://routeplanner.bike.brussels/#12.57/50.8082/4.3543?sb=true&o=4.3350814,50.7936091&d=4.3525832,50.8180457&p=profile1~~

![image](https://user-images.githubusercontent.com/1128068/79323281-e4e50600-7f05-11ea-88ff-e3d540220c1f.png)

**Comment by xivk** [comment]
2.
~~https://routeplanner.bike.brussels/#14.26/50.8456/4.3488?sb=true&o=4.3426616,50.8554610&d=4.3600856,50.8398855&p=profile1~~

![image](https://user-images.githubusercontent.com/1128068/79326347-9e45da80-7f0a-11ea-9ba6-bd90065e7d86.png)

**Comment by xivk** [comment]
3.
~~https://routeplanner.bike.brussels/#14.78/50.8498/4.3477?sb=true&o=4.3519781,50.8481265&d=4.3426616,50.8554610&p=profile1~~

![image](https://user-images.githubusercontent.com/1128068/79326471-ca615b80-7f0a-11ea-9e37-a80e0a9ced63.png)

**Comment by xivk** [comment]
4.
~~https://routeplanner.bike.brussels/#15.46/50.8090/4.3510?sb=true&o=4.3535705,50.8121855&d=4.3477280,50.8075930&p=profile1~~

![image](https://user-images.githubusercontent.com/1128068/79331582-48296500-7f13-11ea-957c-ae849b6c604e.png)

**Comment by pietervdvn** [comment]
1. Incorrect oneway (missing oneway:bicycle=no), fixed by three persons at the same time

2. Piece of inaccessible primary road (I should fix this in the routing profile). Without this piece of road, a small detour is still made [here](https://routeplanner.bike.brussels/#14.85/50.8497/4.3484?sb=true&o=4.3485255,50.8496552&d=4.3508704,50.8484660&p=profile1), due to an `access=no` + `fixme=road closed due to works, resurvey in a few months`

3. See 2.

4. Could not replicate behaviour, fixed by a certain 'Ben Abelshausen' two days ago

**Comment by xivk** [comment]
**snip** moved to https://github.com/anyways-open/cycling-routeplanner/issues/32

**Comment by xivk** [comment]
**snip** moved to https://github.com/anyways-open/cycling-routeplanner/issues/31
