### ISSUE TITLE
Always choose shortest paths when both are networks.

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#78]
This route:

![image](https://user-images.githubusercontent.com/1128068/94253125-1fc37f00-ff25-11ea-8d6d-29c60485dd25.png)

https://routing.anyways.eu/projects/genk/#15.64/50.9805/5.4973?sb=true&o=5.4946983,50.9784319&d=5.4997088,50.9825587&p=profile1

Should be this route:

![image](https://user-images.githubusercontent.com/1128068/94253000-f9054880-ff24-11ea-8192-346cb071ca05.png)

https://routing.anyways.eu/projects/genk/#15.45/50.9802/5.4991?sb=true&o=5.4946983,50.9784319&d=5.4996350,50.9823913&p=profile1

The second route is shorter but is probably taken because it is more attractive because of secondary characteristics. When on a cycle network **none of the other metrics should matter** and the shortest route should always be preferred.

**Comment by xivk** [comment]
Same issue I think:

![image](https://user-images.githubusercontent.com/1128068/94255908-45eb1e00-ff29-11ea-9d77-8f75ce618aff.png)


https://routing.anyways.eu/projects/genk/#16.28/51.00564/5.49544?sb=true&o=5.4956641,51.0048167&d=5.4954934,51.0064783&p=profile1

**Comment by xivk** [comment]
https://routing.anyways.eu/projects/genk/#13.85/50.9750/5.4877?sb=true&o=5.4894362,50.9675169&d=5.4914921,50.9799899&p=profile1

vs

https://routing.anyways.eu/projects/genk/#13.85/50.9750/5.4877?sb=true&o=5.4894362,50.9675169&d=5.4922538,50.9804695&p=profile1

**Comment by pietervdvn** [comment]
1) Blue vs pink/brown: this one could in theory be fixed. In practice, they are very close to each other in length and are pretty instable. Tweaking the routing parameters could be done, but will probably cause issues elsewhere.

2) [this one](https://routing.anyways.eu/projects/genk/#16.28/51.00564/5.49544?sb=true&o=5.4956641,51.0048167&d=5.4954934,51.0064783&p=profile1) has been (partially) fixed by updating the mapping. Note that the route planner is instable here... Compare [a](https://routing.anyways.eu/projects/genk/#16.28/51.00564/5.49544?sb=true&o=5.4956641,51.0048167&d=5.4955284,51.0062572&p=profile1) with [b](https://routing.anyways.eu/projects/genk/#16.28/51.00564/5.49544?sb=true&o=5.4956641,51.0048167&d=5.4955107,51.0063239&p=profile1)

![image](https://user-images.githubusercontent.com/1466478/96870561-60091500-1471-11eb-801d-829981c69edd.png)
![image](https://user-images.githubusercontent.com/1466478/96870614-73b47b80-1471-11eb-9399-513b3e5dde10.png)

3) The purely yellow route is actually _longer_ then the combination of other routes. This is unfixable, except with making extreme tweaks.
