### ISSUE TITLE
Timing for cycling route seems slow

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-frontend#82]
https://routing.anyways.eu/projects/genk/#12.69/50.9827/5.5260?sb=true&o=5.4878576,50.9701927&d=5.5595536,50.9844074&p=profile1

![image](https://user-images.githubusercontent.com/1128068/94257230-44225a00-ff2b-11ea-9c13-8e9a8af43c39.png)

**Comment by xivk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix last issue for Genk before maintenance cycle.](https://trello.com/c/po7ZBhZx/3-fix-last-issue-for-genk-before-maintenance-cycle)

**Comment by xivk** [comment]
@pietervdvn Could you add your advice to this? It looks like this route:

https://geojson.io/#id=gist:xivk/ff0319a3fb8ea230cded5164f4243171&map=14/50.9807/5.5232
https://routing.anyways.eu/projects/genk/#13.51/50.9835/5.5284?sb=true&o=5.4878576,50.9701927&d=5.5577518,50.9848830&p=profile1

Takes about 1hour but it's only 8.16km. Any ideas how to explain this? Is it because of the tracks at the end of the route? There are other routes that are better for timing, this one is also 8.16kms but only 45mins:

https://routing.anyways.eu/projects/genk/#15.56/50.9960/5.5564?sb=true&o=5.4878576,50.9701927&d=5.5581527,50.9964131&p=profile1

**Comment by xivk** [comment]
Also the timings of the regular routes are too high, 45mins for 8km of cycling is too slow. A better estimate is approx. 15kms/hr meaning approx. 33mins.

**Comment by pietervdvn** [comment]
[This](https://www.openstreetmap.org/way/298454572), [this](https://www.openstreetmap.org/way/298454572) and [this](https://www.openstreetmap.org/way/298219874#map=17/50.98389/5.50200) is most probably the culprit. A `highway=path` halves the speed because we assume it is small and unpaved.

For example: [this routing](https://routing.anyways.eu/projects/genk/#13.63/50.9906/5.5112?sb=true&o=5.4992241,50.9825345&d=5.5245878,50.9927552&p=profile1) is the part where the Genk-routes go through forests over (unpaved) paths, needing around 22minutes for 2.7 km, giving us the slow speed of 7.5km/h.

We should ask the city if these paths are truly part of the cycle network, of if they should be updated. If they are paved and wide enough (around 1m), we can retag them as cycleway.

**Comment by pietervdvn** [comment]
I've simply updated the "path" to the proper "highway=cycleway"-tagging. As it is paved; wide and the pavement is visible on the latest aerials, I do think this is the correct tagging for it.
